spring:
  resources:
    static-locations: classpath:static/,file:E:/cmsResources
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  data:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.100.10.8:3306/db_xsysc
      username: root
      password: XHCljpdch1!
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      validation-query-timeout: 3
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: mergeStat,wall,config,slf4j
      connection-properties: config.decrypt=false;druid.stat.slowSqlMillis=5000
  servlet:
      multipart:
        enabled: true
        max-file-size: 30MB
        max-request-size: 30MB
server:
  port: 8180
mybatis:
  mapper-locations: classpath:mysqlMapper/*.xml
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] %-5level %logger{36} - %msg%n"
pagehelper:
  reasonable: true
